# Generated by Django 5.0.6 on 2024-06-14 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_department_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
