# Generated by Django 5.0.6 on 2024-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
