# Generated by Django 5.0.6 on 2024-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_userinfo_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="data",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
