# Generated by Django 5.0.6 on 2024-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_userinfo_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="data",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="size",
        ),
    ]
