# Generated by Django 4.2.1 on 2023-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_department_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="password",
        ),
    ]
