# Generated by Django 4.2.1 on 2023-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_alter_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
