# Generated by Django 4.2.1 on 2023-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_delete_department_delete_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16)),
            ],
        ),
    ]
