# Generated by Django 4.2.1 on 2023-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateField(verbose_name="入职时间"),
        ),
    ]
