# Generated by Django 4.2.1 on 2023-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0002_alter_userinfo_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=20, verbose_name="号码")),
                ("prices", models.IntegerField(default=0, verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "青铜"), (2, "白银"), (3, "黄金"), (4, "钻石"), (5, "星光")],
                        default=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(1, "已使用"), (2, "未使用")], default=2, verbose_name="状态"
                    ),
                ),
            ],
        ),
    ]
